spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: developer
    password: dahoon@9912

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 74160734b993c14263a0d4597c5913cb52de7f59b4f7aba341a831c3c1801dfc