spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://mysql:3306/testdb
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
