name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build test
        env:
          SPRING_PROFILE_ACTIVE: test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar
